
- name: 测试硬盘读写
  hosts: all 
  gather_facts: false
  tasks:
  - name: 测试节点是否可连接
    ping:
  - name: 初始化安装相关
    shell: apt-get update && apt-get install -y screen  fio
    when: init_env == True
  - name: 测试硬盘
    shell: fio -filename=/tmp/test_file -direct=1 -iodepth 1 -thread -rw=readwrite -ioengine=psync -bs=10M -size=2G -numjobs=10 -runtime=60 -group_reporting -name=mytest   >/tmp/fio.log
    when: init_env != True
  - name: 获取日志文件
    fetch:
      src: /tmp/fio.log
      dest: ./result/{{ ansible_host }}.log
      flat: yes
    when: init_env != True




