
- name: up_pass
  hosts: all 
  gather_facts: false
  tasks:
  - name: 修改信息
    debug:
      msg: "{{ansible_user}}@{{ ansible_host}}:{{ ansible_port}}   旧密码{{ ansible_ssh_pass }}   新密码 {{ new_password  }}"
  - name: 传输公钥
    authorized_key:
     user: root
     state: present
     key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: 清理密码文件
    shell: rm -rf /tmp/password
  - name: 写入密码
    copy:
      content: "{{ ansible_user }}:{{ new_password }}"
      dest: /tmp/password
  - name: 修改密码
    shell:  chpasswd </tmp/password